#-------------------------#
# SurvivalGames by Relend #
#-------------------------#

arena:
  spawnpoints:
    - "268.5;26;-0.5;world"
  chests:
    - "269;28;11;world"
  allow-kits: true
  start-amount: 3

chest-items:
  - "bow:1"
  - "stone_sword:1"
  - "arrow:3"