#-------------------------#
# SurvivalGames by Relend #
#-------------------------#

arena:
  world: "world"
  spawnpoints:
    - "268.5;26;-0.5;world"
  chests:
    - "269;28;11;world"
  allow-kits: true
  players-required-start: 3

chest-items:
  - bow:1
  - stone_sword:1
  - arrow:3
  - golden_apple:1
  - leather_helmet:1
  - leather_chestplate:1
  - leather_leggings:1
  - leather_boots:1
  - wooden_axe:1
  - chainmail_boots:1
  - chainmail_helmet:1
  - cooked_beef:4